### ISSUE TITLE
spotify support

### ISSUE THREAD

**Issue by snizzleorg** [linuxserver/docker-daapd#1]
would be nice.

I got this running (mostly) but it is nowhere near as nice as yours. So maybe Its a better idea to integrate the compile flag in your docker container.

**Comment by sparklyballs** [comment]
i could revisit this, but at the time this was built couldn't nail the permissions for spotify compile with running as our dedicated user (abc)

**Comment by sparklyballs** [comment]
i think i may have cracked it, i had the prefix for spotifiy at /usr/local , changed it to /usr and daapd no longer crashes with the spotifiy module compiled.

i don't have a spotifiy account so can't test.

**Comment by snizzleorg** [comment]
I have an account and obviously can test.
I got it to compile correctly here:

https://github.com/snizzleorg/forked-daapd-docker

I think the important bit is this part in the Dockerfile

```
RUN wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add - &&\
  wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list &&\
  apt-get update &&\
  apt-get install -qy --force-yes libspotify-dev
```

maybe there is a better way....

**Comment by sparklyballs** [comment]
i've already compiled it with spotifiy support. 

```
curl -o /tmp/spotify_tar.gz -L https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz && \
mkdir -p /tmp/spotify && \
tar xvf /tmp/spotify_tar.gz -C /tmp/spotify --strip-components=1 && \
cd /tmp/spotify && \
make install prefix=/usr
```

**Comment by snizzleorg** [comment]
awesome. will try it out as soon as I find some time.

**Comment by tbrtje** [comment]
why was Spotify-support removed?

**Comment by CHBMB** [comment]
@thies226j Suggest you look [here](https://github.com/linuxserver/docker-daapd/issues/30) and [here](https://github.com/linuxserver/docker-daapd/issues/29)

In short, this container is broken and unless someone offers to help maintain it, we will have to drop it.
