### ISSUE TITLE
the image for linuxserver/forked-daapd version 25.0 is missing web interface

### ISSUE THREAD

**Issue by kylegoetz** [linuxserver/docker-daapd#16]
The relevant part of the logs says:

    [2018-01-28 18:06:25] [  LOG]     main: Forked Media Server Version 25.0 taking off
    [  LOG]     main: Forked Media Server Version 25.0 taking off

So version 25.0 is running. However, if you see the underlying code at https://github.com/ejurgensen/forked-daapd version 25.0 has a functional web interface. But the container I installed (just a few days ago, built *after* the introduction of the web interface (sometime in Dec 2017), the web interface is non-existent. You get a prompt to log in, but the interface code itself does not exist. According to the forked-daapd maintainers, this is because the web interface does not exist.

I do not have a recommendation. I guess you need to re-build the container or build it with the web interface enabled or something?

I've created a PR for the forked-daapd project that creates a new release I called v25.1. v25.0, which is the current version for forked-daapd, is over 200 commits behind the latest code, which would be v25.1.

**Comment by ejurgensen** [comment]
The web interface is recent enough that it is in trunk, not in 25.0. It will become part of the next release, probably within a month or two.

**Comment by sparklyballs** [comment]
we'll wait until the new release

**Comment by christophkreutzer** [comment]
v26.0 has been released :tada:
