### ISSUE TITLE
mdns

### ISSUE THREAD

**Issue by fergalom** [linuxserver/docker-daapd#22]
Latest docker-daapd image

Docker compose
`forked-daapd:
        container_name: forked-daapd    
        image: linuxserver/daapd
        network_mode: "host"
        volumes:
          - /opt/forked-daapd:/config
          - /etc/localtime:/etc/localtime:ro
          - /opt/NASmusic:/music`

In the logs
`GID/UID
-----------------------------------
User uid:    911
User gid:    911
-----------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing... 
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Failed to set ownership on logfile: Operation not permitted
[  LOG]     main: Forked Media Server Version 26.2 taking off
[  LOG]     main: Built with:
[  LOG]     main: - ffmpeg
[  LOG]     main: - iTunes XML
[  LOG]     main: - LastFM
[  LOG]     main: - Chromecast
[  LOG]     main: - MPD
[  LOG]     main: - Device verification
[  LOG]     main: - Websockets
[  LOG]     main: - ALSA
[  LOG]     main: - Webinterface
[  LOG]     main: mDNS init
[  LOG]     mdns: Avahi state change: Client connecting
[  LOG]       db: Now vacuuming database, this may take some time...
[  LOG]       db: Database OK with 6844 active files and 7 active playlists
[  LOG]     mdns: Failed to create service browser: Bad state
[  LOG]     raop: Could not add mDNS browser for AirPlay devices
[  LOG]     mdns: Failed to create service browser: Bad state
[  LOG]     cast: Could not add mDNS browser for Chromecast devices
[  LOG]     mdns: Failed to create service browser: Bad state
[FATAL]   remote: Could not browse for Remote services
[FATAL]     main: Remote pairing service failed to start
[  LOG]     main: MPD deinit
[  LOG]     main: HTTPd deinit
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
`

Seems like an issue with mdns??

**Comment by tobbenb** [comment]
You need to specify the PGID and PUID. Check the README for what paramteres that are needed.

**Comment by fergalom** [comment]
Have tried that also, my dockeruser is admin whose UID is 1000

`    forked-daapd:
        container_name: forked-daapd    
        image: linuxserver/daapd
        network_mode: "host"
        volumes:
          - /opt/forked-daapd:/config
          - /etc/localtime:/etc/localtime:ro
          - /opt/NASmusic:/music
        environment:
          - PGID=1000
          - PUID=1000`

Same result:
`
Brought to you by linuxserver.io


We gratefully accept donations at:


https://www.linuxserver.io/donate/


-------------------------------------


GID/UID


-------------------------------------




User uid:    1000


User gid:    1000


-------------------------------------




[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 30-dbus: executing... 


[cont-init.d] 30-dbus: exited 0.


[cont-init.d] 40-config: executing... 


[cont-init.d] 40-config: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.


Failed to set ownership on logfile: Operation not permitted


[  LOG]     main: Forked Media Server Version 26.2 taking off


[  LOG]     main: Built with:


[  LOG]     main: - ffmpeg


[  LOG]     main: - iTunes XML


[  LOG]     main: - LastFM


[  LOG]     main: - Chromecast


[  LOG]     main: - MPD


[  LOG]     main: - Device verification


[  LOG]     main: - Websockets


[  LOG]     main: - ALSA


[  LOG]     main: - Webinterface


[  LOG]     main: mDNS init


[  LOG]     mdns: Avahi state change: Client connecting


[  LOG]       db: Now vacuuming database, this may take some time...


[  LOG]       db: Database OK with 6844 active files and 7 active playlists


[  LOG]     mdns: Failed to create service browser: Bad state


[  LOG]     raop: Could not add mDNS browser for AirPlay devices


[  LOG]     mdns: Failed to create service browser: Bad state


[  LOG]     cast: Could not add mDNS browser for Chromecast devices


[  LOG]     mdns: Failed to create service browser: Bad state


[FATAL]   remote: Could not browse for Remote services


[FATAL]     main: Remote pairing service failed to start


[  LOG]     main: MPD deinit


[  LOG]     main: HTTPd deinit


Found user 'avahi' (UID 86) and group 'avahi' (GID 86).


Successfully dropped root privileges.


avahi-daemon 0.7 starting up.


WARNING: No NSS support for mDNS detected, consider installing nss-mdns!


Loading service file /etc/avahi/services/sftp-ssh.service.


Loading service file /etc/avahi/services/ssh.service.


Joining mDNS multicast group on interface vethdda8319.IPv6 with address fe80::64c9:b0ff:fec4:a950.


New relevant interface vethdda8319.IPv6 for mDNS.


Joining mDNS multicast group on interface veth56fd09c.IPv6 with address fe80::c404:78ff:fe57:f930.


New relevant interface veth56fd09c.IPv6 for mDNS.


Joining mDNS multicast group on interface vethf083a4c.IPv6 with address fe80::4834:6aff:fe0b:e290.


New relevant interface vethf083a4c.IPv6 for mDNS.


Joining mDNS multicast group on interface vethd791e40.IPv6 with address fe80::4087:93ff:fe8a:7e06.


New relevant interface vethd791e40.IPv6 for mDNS.


Joining mDNS multicast group on interface vethec0779e.IPv6 with address fe80::2483:2cff:feb7:7e2c.


New relevant interface vethec0779e.IPv6 for mDNS.


Joining mDNS multicast group on interface veth11ee08b.IPv6 with address fe80::64a8:f4ff:febd:ef5e.


New relevant interface veth11ee08b.IPv6 for mDNS.


Joining mDNS multicast group on interface veth652d594.IPv6 with address fe80::bcb0:17ff:fe36:dfa3.


New relevant interface veth652d594.IPv6 for mDNS.


Joining mDNS multicast group on interface vethfddc15d.IPv6 with address fe80::dc05:deff:fea4:2cfc.


New relevant interface vethfddc15d.IPv6 for mDNS.


Joining mDNS multicast group on interface vetha270e95.IPv6 with address fe80::c46:aff:fe37:f8b3.


New relevant interface vetha270e95.IPv6 for mDNS.


Joining mDNS multicast group on interface vethd00adb1.IPv6 with address fe80::aca1:beff:fec7:2a7f.


New relevant interface vethd00adb1.IPv6 for mDNS.


Joining mDNS multicast group on interface br-bf1905d57eac.IPv6 with address fe80::42:67ff:fe37:15e5.


New relevant interface br-bf1905d57eac.IPv6 for mDNS.


Joining mDNS multicast group on interface br-bf1905d57eac.IPv4 with address 172.19.0.1.


New relevant interface br-bf1905d57eac.IPv4 for mDNS.


Joining mDNS multicast group on interface br-ecc3b155ee1b.IPv4 with address 172.20.0.1.


New relevant interface br-ecc3b155ee1b.IPv4 for mDNS.


Joining mDNS multicast group on interface br-e18f05f2cb12.IPv4 with address 172.18.0.1.


New relevant interface br-e18f05f2cb12.IPv4 for mDNS.


Joining mDNS multicast group on interface docker0.IPv6 with address fe80::42:afff:fe98:2cbe.


New relevant interface docker0.IPv6 for mDNS.


Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.


New relevant interface docker0.IPv4 for mDNS.


Joining mDNS multicast group on interface eno1.IPv6 with address fe80::d782:8bea:60bc:f574.


New relevant interface eno1.IPv6 for mDNS.


Joining mDNS multicast group on interface eno1.IPv4 with address 192.168.1.4.


New relevant interface eno1.IPv4 for mDNS.


Network interface enumeration completed.


Registering new address record for fe80::64c9:b0ff:fec4:a950 on vethdda8319.*.


Registering new address record for fe80::c404:78ff:fe57:f930 on veth56fd09c.*.


Registering new address record for fe80::4834:6aff:fe0b:e290 on vethf083a4c.*.


Registering new address record for fe80::4087:93ff:fe8a:7e06 on vethd791e40.*.


Registering new address record for fe80::2483:2cff:feb7:7e2c on vethec0779e.*.


Registering new address record for fe80::64a8:f4ff:febd:ef5e on veth11ee08b.*.


Registering new address record for fe80::bcb0:17ff:fe36:dfa3 on veth652d594.*.


Registering new address record for fe80::dc05:deff:fea4:2cfc on vethfddc15d.*.


Registering new address record for fe80::c46:aff:fe37:f8b3 on vetha270e95.*.


Registering new address record for fe80::aca1:beff:fec7:2a7f on vethd00adb1.*.


Registering new address record for fe80::42:67ff:fe37:15e5 on br-bf1905d57eac.*.


Registering new address record for 172.19.0.1 on br-bf1905d57eac.IPv4.


Registering new address record for 172.20.0.1 on br-ecc3b155ee1b.IPv4.


Registering new address record for 172.18.0.1 on br-e18f05f2cb12.IPv4.


Registering new address record for fe80::42:afff:fe98:2cbe on docker0.*.


Registering new address record for 172.17.0.1 on docker0.IPv4.


Registering new address record for fe80::d782:8bea:60bc:f574 on eno1.*.


Registering new address record for 192.168.1.4 on eno1.IPv4.


[  LOG]     main: Player deinit


Server startup complete. Host name is dockerhost.local. Local service cookie is 2683638614.


Service "dockerhost" (/etc/avahi/services/ssh.service) successfully established.


Service "dockerhost" (/etc/avahi/services/sftp-ssh.service) successfully established.`

**Comment by tobbenb** [comment]
And the issue is? You haven't said anything other than mdns issue, which doesn't say much.
Can you get to the web interface?

**Comment by fergalom** [comment]
No access to web interface.
Using "mpc -h x.y.z.w outputs" from another lan terminal gives "error no route to host"
I'm referring to mdns as thats what appears to be failing in the logs
