### ISSUE TITLE
apple remote app causes crash

### ISSUE THREAD

**Issue by lixee** [linuxserver/docker-daapd#25]
The latest version is running absolutely fine as long as I don’t use the apple remote app AND have covers saved in my music folder or embedded in the files directly.

Covers aren’t causing any crashes when using iTunes to load up the library, but the remote app does. If I remove every cover saved (jpgs and embedded in the music files) the remote app does work without causing a crash. If I have covers saved and don’t use the remote app also everything works fine.

But of course it would be nice to use the iOS remote app and also use cover (jpgs and embedded), used to work in earlier versions.

**Comment by aptalca** [comment]
We don't have a maintainer for this image at the moment. None of the team members are using it, most lack the hardware and the iTunes software.

**Comment by thelamer** [comment]
This image has been depreciated
