### ISSUE TITLE
No connection on Synology Diskstation

### ISSUE THREAD

**Issue by throatwobbler** [linuxserver/docker-daapd#27]
Hi,

I'm using Docker on a Synology Diskstation 918+ and would like to run forked-daapd on it.
After the container is started I can access the web gui but always get the message "Connection lost. Reconnecting...". But it never reconnects.

The only issues I can see in the log file are the two FATAL messages. But I don't know a lot about linux and its services.

I tried I mapping ports 3688, 3689 and 6600 (tcp and udp) and use my "xbmc" user as "PUID". I also tried the synology-docker-gui option "Execute container with high privilege" which gives the container root privileges. Nothing helped.

Here is my log file:

[daapd.txt](https://github.com/linuxserver/docker-daapd/files/2898100/daapd.txt)

Would be really nice if you could help me with that issue because I really love mtdaapd.

Thanks in advance
 Timo

EDIT: I also tried starting from the command line using this command:
`docker run -d --network=host --name=firefly -e PUID=1029 -e PGID=100 -v /volume2/docker/daapd/:/config -v /volume1/music/:/music linuxserver/daapd`
But I can't see the server in any application and the web frontend still tries reconnecting.
This is the log file:

[firefly.txt](https://github.com/linuxserver/docker-daapd/files/2904466/firefly.txt)

**Comment by nicx** [comment]
I have the same problem, any news to this?

**Comment by eRaz3r** [comment]
Any news about this? Got the same issue and no solution. Also there are no tags and no artwork shown. @nicx and @throatwobbler can you confirm that?

**Comment by nicx** [comment]
yes still waiting for a fix :(

**Comment by eRaz3r** [comment]
Thanks for your reply. I look forward to solve this, maybe over the config. We will see.

**Comment by msw141** [comment]
same issue, running docker container on OpenMediaVault

**Comment by thelamer** [comment]
This image has been depreciated
