### ISSUE TITLE
Build broken at head 

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-daapd#29]
Currently even with the previous version of Alpine this build is broken at head.

**Comment by thelamer** [comment]
```
checking for library containing antlr3BaseRecognizerNew...... no
configure: error: in `/tmp/source/forked-daapd':
configure: error: Function antlr3BaseRecognizerNew in libantlr3c not found.
Install ANTLR3 C runtime in the default include path, or alternatively set
library specific environment variables ANTLR3C_CFLAGS
and ANTLR3C_LIBS.
```

**Comment by chme** [comment]
I got a working build in https://github.com/chme/docker-daapd/tree/fixbuild (only tested x86_64)

My knowledge about docker and alpine linux is very limited. But from my tinkering, it looks like the libantlr3(-dev) package is broken. `apk add libantlr3c-dev` did only install the header files and not the shared library. Adding `apk add libantlr3c` did fix the build but there are problems running the container (seems like forked-daapd keeps crashing and restarting).

Building libantlr3c in the docker file seems to be working (only did a short test).

**Comment by thelamer** [comment]
This image has been depreciated

**Comment by BernsteinA** [comment]
new PR https://github.com/linuxserver/docker-daapd/pull/32
