### ISSUE TITLE
Please Update to forked-daapd 27.2

### ISSUE THREAD

**Issue by Hackashaq666** [linuxserver/docker-daapd#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Please update the container to use forked-daapd 27.2 which fixes album art bug.

Also posted by @lldsolitude in https://github.com/linuxserver/docker-daapd/issues/34#issuecomment-660805815_

Not sure how @lldsolitude fixed his container, I keep getting 27.1 forked-dappd when I re-create the container.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Docker logs

_Originally posted by @lldsolitude in https://github.com/linuxserver/docker-daapd/issues/34#issuecomment-660805815_

**Comment by aptalca** [comment]
@Hackashaq666 
I just realized we had the build triggers disabled for this because it wasn't building for a long time.
It has since then been fixed. I'll go ahead and update the triggers and push a new build for 27.2. Can you please try it and let us know if it works fine? I'll ping again after it's pushed.

Thanks.

**Comment by Hackashaq666** [comment]
Great, I will let you know if it works.

**Comment by aptalca** [comment]
@Hackashaq666 27.2 pushed to docker hub

**Comment by Hackashaq666** [comment]
Updated my container and it looks good!
Thanks for the fast response!
