### ISSUE TITLE
Spotify connect feature for forked-daapd not working

### ISSUE THREAD

**Issue by Depechie** [linuxserver/docker-daapd#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Able to select forked-daapd as play target inside the spotify app.

## Current Behavior
You can select it, but nothing is played on the selected output devices. And selecting it in Spotify app is not smooth, often fails ( seems like network communication for it is not working great ).

I actually first added this issue to the original OwnTone repo, thinking the Spotify connect capability came with the new Spotify linking that we got in version 28.2. https://github.com/owntone/owntone-server/issues/1313
But the maintainer said it is from the docker creation in LinuxServer. Seems librespot is being added.

## Steps to Reproduce
1. Open the Spotify app
2. Play a song
3. Press the connected devices icon on the left bottom
4. Select forked-daapd as target
5. Notice no music being played through the output

## Environment
**OS:** Raspbian on Raspberry pi 3B+
**CPU architecture:** arm32
**How docker service was installed:**
Installed docked through portainer that is running on the raspberry pi.

**Comment by ejurgensen** [comment]
@BernsteinA you may consider removing librespot from the image, since version 28.2 of OwnTone can now play Spotify (but not Spotify Connect) without any third-party stuff.

Also consider renaming to owntone.

**Comment by Depechie** [comment]
Although I agree with @ejurgensen to first try to have a clean docker with the build in features of OwnTone, I must say I would be very keen on also having that Spotify connect integration.
The iOS remote app works, but the Spotify app is just miles ahead in usability.

Seems SpoCon is the way to go? https://jorisvanhecke.be/homepod-spotify-connect/

**Comment by bverhagen** [comment]
See https://github.com/owntone/owntone-server/pull/1253: Librespot shouldn't have been merged anymore. I created a PR to disable it and use the default Spotify implementation: https://github.com/linuxserver/docker-daapd/pull/55.

 @Depechie Integration between Owntone and Librespot using a named pipe is far from ideal (see new PR for more details). I don't recommend combining them at this moment, unless you are prepared to work on the rough edges yourself. Personally, I use the web interface in Owntone for playing Spotify. While less fancy than the Spotify app itself, it works well and intuïtively, which is not always the case for the Spotify app.

**Comment by Depechie** [comment]
Commenting to get out of the stale bot :)

**Comment by Depechie** [comment]
Commenting to get out of the stale bot :)

**Comment by BernsteinA** [comment]
@Depechie what's the current status of this issue?

**Comment by Depechie** [comment]
I think nobody took a stab at it currently...
