### ISSUE TITLE
Container won't start properly in latest release 28.3-ls69

### ISSUE THREAD

**Issue by lldsolitude** [linuxserver/docker-daapd#60]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container should start properly.

## Current Behavior

Container won't start properly after upgrading to the latest image and rebooting. Web interface can't be accessed.
Last version 28.3-ls68 doesn't have this problem. Seems to be caused by rebasing to Alpine 3.15 in 28.3-ls69.

## Steps to Reproduce

1. Pull latest image and recreate container. The new container can start normally before reboot.
2. Reboot. Container can't start.

## Environment
**OS:** Openmediavault 6 (Debian 11)
**CPU architecture:** x86_64
**How docker service was installed:** from official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
  daapd:
    image: linuxserver/daapd
    container_name: daapd
    network_mode: host
    environment:
      - PUID=119
      - PGID=65534
      - TZ=Asia/Shanghai
    volumes:
      - /var/lib/daapd:/config
      - /srv/dev-disk-by-label-Data/Data/Music:/music
      - '/srv/dev-disk-by-label-Data/Data/Music Library:/music_library'
      - /tmp/audio_pipe:/audio_pipe
    restart: unless-stopped
```

## Docker logs

The following entries repeat every second.
```
[2022-03-06 00:15:31] [  LOG]     main: OwnTone version 28.3 taking off
[2022-03-06 00:15:31] [  LOG]     main: Built with:
[2022-03-06 00:15:31] [  LOG]     main: - ffmpeg
[2022-03-06 00:15:31] [  LOG]     main: - Spotify
[2022-03-06 00:15:31] [  LOG]     main: - librespot-c
[2022-03-06 00:15:31] [  LOG]     main: - LastFM
[2022-03-06 00:15:31] [  LOG]     main: - Chromecast
[2022-03-06 00:15:31] [  LOG]     main: - MPD
[2022-03-06 00:15:31] [  LOG]     main: - Websockets
[2022-03-06 00:15:31] [  LOG]     main: - ALSA
[2022-03-06 00:15:31] [  LOG]     main: - Webinterface
[2022-03-06 00:15:31] [  LOG]     main: - Regex
[2022-03-06 00:15:31] [  LOG]     main: mDNS init
Assertion failed: client (client.c: avahi_client_errno: 791)
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).dbus-daemon[1115]: 
Failed to start message bus: The pid file "/run/dbus/dbus.pid" exists, if the message bus is not running, remove this file
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
dbus_bus_get_private(): Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
WARNING: Failed to contact D-Bus daemon.
avahi-daemon 0.8 exiting.
Failed to set ownership on logfile: Operation not permitted
```

**Comment by thespad** [comment]
Looks like the dbus path has changed, we do this https://github.com/linuxserver/docker-daapd/blob/master/root/etc/cont-init.d/30-dbus#L8 at the moment.

Will do some tests and if necessary make a PR to fix it.

**Comment by pinguinpfleger** [comment]
As a solution for the meantime, you can
`docker exec daapd rm /run/dbus/dbus.pid`

**Comment by thespad** [comment]
@lldsolitude can you test with `lspipepr/daapd:28.3-pkg-ba5cdc8f-pr-61` and see if it resolves your issue.

**Comment by lldsolitude** [comment]
@TheSpad The issue is resolved. Thank you.
