### ISSUE TITLE
fatal: unable to remove /var/run: Read-only file system

### ISSUE THREAD

**Issue by crkinard** [linuxserver/docker-daapd#67]
Completely fresh install and getting this on run.

```
2022-09-28 12:11:50.876545+00:00/package/admin/s6-overlay/libexec/preinit: notice: /var/run is not a symlink to /run, fixing it
2022-09-28 12:11:50.876878+00:00s6-rmrf: fatal: unable to remove /var/run: Read-only file system
2022-09-28 12:11:50.876958+00:00s6-overlay-suexec: fatal: child failed with exit code 111
```

**Comment by crkinard** [comment]
`Linux dock 5.10.142+truenas #1 SMP Mon Sep 26 18:20:46 UTC 2022 x86_64 GNU/Linux`
`TrueNAS-SCALE-22.02.4
`
No way to post images. No config file as the interface is GUI only. Closest thing would be this docker-compose.

```
version: "2.1"
services:
  daapd:
    image: lscr.io/linuxserver/daapd:latest
    container_name: daapd
    environment:
      - TZ=America/New_York
    volumes:
      - /mnt/store/_docker/daapd/config:/config
      - /mnt/store/_docker/daapd/custom-cont-init.d:/custom-cont-init.d
      - /mnt/store/media/Music:/music
    restart: unless-stopped
```

**Comment by BernsteinA** [comment]
@crkinard are you successfully running any other docker containers on that machine? (any other linuxserver.io images?)

**Comment by crkinard** [comment]
5 other linuxserver.io containers running fine.

**Comment by drizuid** [comment]
We don't offer support for truenas scale and we do not test on it. It looks like some filesystem issue, but you didn't provide container logs so not much we can do outside of guessing.
