### ISSUE TITLE
[FEAT] Will you be open to adding support for PulseAudio? 

### ISSUE THREAD

**Issue by MickMorley** [linuxserver/docker-daapd#70]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Adding the `--with-pulseaudio` config is required when installing OwnTone.  I have tested this by modifying your Dockerfile and installing it on my Unraid server.

Let me know if you are OK with it and I will make a pull request or someone can simple add `pulseaudio-dev` package to your both your build stage and runtime stage. And add `--with-pulseaudio \` to the `./configure` command.

### Reason for change

I use a networked PulseAudio server to output audio to multiple zones in a HomeAudio setup. The PulseAudio plugin works amazing on OwnTone.

### Proposed code change

- `pulseaudio-dev` package
`- --with-pulseaudio \`

**Comment by aptalca** [comment]
Sure, feel free to open a PR. Are you sure the dev package is required runtime?

**Comment by MickMorley** [comment]
Thank you @aptalca, I will run a few more local dockerfile installs on my Unraid server and confirm if its needed at runtime.

**Comment by MickMorley** [comment]
Hi @aptalca I ran some tests and it does look like the dev package is required at runtime.
