### ISSUE TITLE
Owntone 28.5 restarts in container continuously

### ISSUE THREAD

**Issue by squirtbrnr** [linuxserver/docker-daapd#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Owntone does not start.  Instead it continuously restarts inside the container.  The web interface doesn't even load.

### Expected Behavior

Owntone should start and not restart.  The webpage should be accessible.

### Steps To Reproduce

create a docker container with any version starting with 28.5-ls104 (28.5.20230225) and newer (any image rebased to Alpine 3.17).  Observe docker logs and see own tone continuously restart. Release 28.5-ls103 (28.5.20230223) works fine.

### Environment

```markdown
- OS: Synology DSM 6.2.4-25556 Update 6
- Docker 20.10.3-0554 from Synology Package Center
- docker image lscr.io/linuxserver/daapd:28.5.20230225
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker create --name=owntone --restart no -v /volume1/docker/owntone/config:/config -v /volume1/Earth:/music -v /etc/localtime:/etc/localtime:ro -e TZ=America/Chicago -e PUID=1040 -e PGID=100 --net=host lscr.io/linuxserver/daapd:28.5.20230225
```

### Container logs

```bash
https://pastebin.com/aYh6YpLt
```

**Comment by aptalca** [comment]
Please post the logs on pastebin or the like. I'm not going to download and open random uploaded files.

Our ci tests start just fine
https://ci-tests.linuxserver.io/linuxserver/daapd/latest/index.html

**Comment by squirtbrnr** [comment]
added pastebin of latest logs from a test and removed the export from Synology docker. Synology docker exports logs in descending order by date/time stamp.

I tried creating a brand new docker container with no database and the stock config.  it still restarts.

**Comment by squirtbrnr** [comment]
Any comments on this? I submitted the docker logs as requested. A fresh docker with the default config still restarts.

**Comment by BernsteinA** [comment]
Did you read the log yourself?Have you tried doing a web search for the error you’re receiving?Fatal: getentropy is not supported: Function not implemented Do you have other containers running successfully on the same host?

**Comment by squirtbrnr** [comment]
Yes I read the log.  Yes I searched for getentropy not supported.  Yes I have many other docker containers running on the same host.  Owntone 28.5.20230223 runs with no issues.

**Comment by squirtbrnr** [comment]
Still an issue.  Not sure why I never got a response after following directions.

**Comment by BernsteinA** [comment]
It’s because we’re all volunteers and none of us has a synology to test on

**Comment by aptalca** [comment]
The pastebin logs expired, so I can't see it, but try option 2 (libseccomp bit) from here: https://docs.linuxserver.io/faq#jammy

**Comment by squirtbrnr** [comment]
Thanks for the suggestion.  Doesn't look like the security options changed anything.  Still get the same message "Fatal: getentropy is not supported: Function not implemented" and the service reboots inside the container.  Yes Synology uses a pretty out of date docker engine (20.10.3-0554 according to their package center).

**Comment by squirtbrnr** [comment]
Still an issue.  Is there a way to add the missing function "getentropy"? Like build a separate image?

**Comment by thespad** [comment]
It's not something you can add, I'm assuming you're using a Synology unit with a 3.x kernel, which doesn't support the getentropy syscall. Your options are use an older image or a system with a newer kernel, as Synology refuse to do kernel updates.

**Comment by squirtbrnr** [comment]
Bummer. I was afraid that was the case. I am on DSM 6.2.4 but my unit supports up to DSM 7.1. I wonder if I went to DSM 7.1 it would include a newer kernel?

**Comment by thespad** [comment]
Nope, sadly not. The kernel version it ships with is what you're stuck with short of minor patches. This is a 916+ running DSM 7.2
```
$ uname -a
Linux NAS1 3.10.108 #64561 SMP Fri May 19 01:32:53 CST 2023 x86_64 GNU/Linux synology_braswell_916+
```

**Comment by squirtbrnr** [comment]
Oh that stinks. Yeah I just checked and I’m at 3.10.105. Oh well. Thanks for clarifying and explaining this to me.
