### ISSUE TITLE
[BUG] Podcasts subscriptions get deleted after container update

### ISSUE THREAD

**Issue by michi1972-dev** [linuxserver/docker-daapd#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Everything works exept rss subscriptions being held through update of container. cache.db is in extra volume.

### Expected Behavior

subriptions will be saved through update

### Steps To Reproduce

subscribe to any podcast

### Environment

```markdown
- OS:
- How docker service was installed:
standard docker install on debian 12 / omv7
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  daapd:
    image: lscr.io/linuxserver/daapd:latest
    container_name: daapd
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - ip-range=10.0.0.0/8
    volumes:
      - /zfs-pool/container-data/daapd/data:/config
      - /zfs-pool/music:/music
    restart: unless-stopped
    mem_reservation: "120M"
    mem_limit: "500M"
    cpus: "0.3"
```

### Container logs

```bash
standard, no errors
```

**Comment by michi1972-dev** [comment]
it's still a problem

**Comment by BernsteinA** [comment]
Can you provide clearer repro steps for those of us who don’t normally use this feature? (I’m a maintainer on this repo but personally I only use it for iTunes library serving)

**Comment by michi1972-dev** [comment]
Sorry for letting you wait, was on holidays. It's easy: Just subscribe to a podcast of your choice, check if it's working (it normally should), wait for a new release, install that to your docker (in my case it does automatically, I'm using OMV7 with docker extension.) 

You can see after that, all subscriptions of all podcast channels are gone, also the marking if something was head or not. I'm hoping you find the error, maybe I have done s.th. wrong. Did I forget a volume? I've used the compose info on linuxserver site.

Please, if anyone has an idea: please contribute.

@BernsteinA Aaron, where you able to replicate the problem in any way?

(EDIT: typo and corrections of grammar)

**Comment by michi1972-dev** [comment]
Still cannot figure out where the problem is.

**Comment by michi1972-dev** [comment]
.?

**Comment by michi1972-dev** [comment]
Gets still deleted

**Comment by michi1972-dev** [comment]
No one knows how to solve this problem?

**Comment by j0nnymoe** [comment]
Are you able to find where the podcasts are stored within the container?

**Comment by j0nnymoe** [comment]
Looks like the default path in the owntone conf is `/Podcasts` - map that as a volume.

**Comment by michi1972-dev** [comment]
Hello @j0nnymoe,

thank you for your reply! I've tried to find the /Podcasts directory - but there is none:

`root@nas:/# ls -l
total 111
drwxr-xr-x   1 abc  abc            2 Aug 24 13:31 app
drwxr-xr-x   1 root root          41 Aug 24 13:31 bin
-rw-r--r--   1 root root          72 Aug 27 15:08 build_version
drwxr-xr-x   2 root root         237 Aug 24 13:31 command
drwxr-sr-x   3 abc  abc            5 Jul 18 15:27 config
drwxr-xr-x   2 abc  abc            2 Aug 28 02:32 daapd-pidfolder
drwxr-xr-x   1 abc  abc            3 Aug 28 02:32 defaults
drwxr-xr-x   5 root root         340 Sep  4 02:03 dev
-rwxr-xr-x   1 root root       25305 Jan  1  1970 docker-mods
drwxr-xr-x   1 root root           9 Sep  4 02:03 etc
drwxr-xr-x   2 root root           2 Aug 24 13:31 home
-rwxr-xr-x   1 root root        1012 Nov 20  2023 init
drwxr-xr-x   1 root root           9 Aug 27 15:08 lib
drwxr-xr-x   2 root root           2 Aug 24 13:31 lsiopy
drwxr-xr-x   5 root root           5 Aug 24 13:31 media
drwxr-xr-x   2 root root           2 Aug 24 13:31 mnt
drwxrwsr-x  85 root messagebus    86 Apr 16 11:45 music
drwxr-xr-x   2 root root           2 Aug 24 13:31 opt
drwxr-xr-x   6 root root           6 Aug 24 13:31 package
dr-xr-xr-x 643 root root           0 Sep  4 02:03 proc
drwx------   2 root root           2 Aug 24 13:31 root
drwxr-xr-x   1 root root          12 Sep  4 02:03 run
drwxr-xr-x   1 root root          10 Aug 24 13:31 sbin
drwxr-xr-x   2 root root           2 Aug 24 13:31 srv
dr-xr-xr-x  13 root root           0 Aug 31 18:48 sys
drwxrwxrwt   1 root root           3 Aug 28 02:32 tmp
drwxr-xr-x   1 root root           3 Aug 27 15:09 usr
drwxr-xr-x   1 root root           4 Aug 24 13:31 var
root@nas:/# 
``
Can you please assist? At the moment I'm listening to a podcast. No directory.

**Comment by j0nnymoe** [comment]
I don't use daapd so zero idea how it works. You need to find where it is saving your podcasts to, I would suggest checking your config file within the `/config` mount.

**Comment by michi1972-dev** [comment]
In my owntone.conf I've found this:

	# /music/Podcasts, you can set this to "/Podcasts".
	podcasts = { "/Podcasts" }
#	name_podcasts   = "Podcasts"

I've created this directory manually. No change.

What can I do now?

**Comment by j0nnymoe** [comment]
You likely need to recreate the container with that volume

**Comment by michi1972-dev** [comment]
Did that. All podcasts are gone. Folder /Podcasts is empty, even after new podcasts. This is a bug, still don't know what to do.

**Comment by j0nnymoe** [comment]
If you can figure out what folder they're being stored in, then we can figure out what's happening. Also I would suggest not using the podcast feature or at least don't update the container while this is happening.

**Comment by ejurgensen** [comment]
The "Podcasts" folder has nothing to do with this issue. The folder is for adding mp3's and getting OwnTone to understand that they are Podcasts, but this issue is about RSS subscriptions. They are saved in songs3.db, so if they are disappearing then it's because that file isn't persisted.

**Comment by michi1972-dev** [comment]
Again, the Podcasts subscriptions are all gone. I obviously did not find the correct issue on that. songs3.db is in data folder: 

`---
services:
  daapd:
    image: lscr.io/linuxserver/daapd:latest
    container_name: daapd
    network_mode: host
    environment:
      - ip-range=10.0.0.0/8
    volumes:
      - /zfs-pool/container-data/daapd/data:/config
      - /zfs-pool/container-data/daapd/avahi/avahi-daemon.conf:/etc/avahi/avahi-daemon.conf
      - /zfs-pool/music:/music
      - /zfs-pool/music/Podcasts:/Podcasts
    restart: unless-stopped
    mem_reservation: "20M"
    mem_limit: `"600M"`

I'm a little bit frustrated right now, I really cannot find the bug ...
